---
version: "3.7"
services:
  termproject:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: termproject
    volumes:
      - ./logs:/home/node/logs
      - ./csv:/home/node/files
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - proxy
      
  db:
    image: postgres:15-alpine3.17
    ports:
      - 6632:5432
    restart: always
    container_name: termdb
    env_file:
      - .postgres.env
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  proxy:
    external: True
      